### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by syossan27** [syossan27/lgtm-generator#1]
- [x] Implement Google Image Search
- [x] Display search result
  - [x] Display error image, when get error image.
- [x] Display image on canvas
- [x] Loading image by click image
- [x] Display controllable text on canvas
- [x] If access to /edit (post no image), redirect /
- [x] Select font and Setting font
- [x] Download LGTM image

**Row-Primary**
- [x] Can use complicated search-keyword
- [ ] ~~If browser-back from /edit, keep search-text and search-result~~
- [ ] Transition page by carousel annimation
- [ ] Display SNS Icons
- [x] Check API securiy
- [ ] ~~Display LoadingImage, will load LGTM image~~
